version: "3"
services:
  app:
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./backend/.env
    build:
      context: .
      dockerfile: ./backend/Dockerfile

    ports:
      - "3000:3000"

  database:
    image: postgres:16-alpine
    env_file:
      - ./backend/.env
    healthcheck:
      interval: 1s
      test: "pg_isready --username=postgres"
    ports:
      - "5440:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
